FROM gocd/gocd-agent-alpine-3.6:v18.1.0

RUN apk --no-cache add \
    docker \
    python3 \
    make

RUN pip3 install --upgrade pip && \
    pip3 install virtualenv

RUN adduser go docker

COPY agent_start.sh /
ENTRYPOINT ["/agent_start.sh"]
