---
version: '3'
services:
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    environment:
      GO_SERVER_SYSTEM_PROPERTIES: '-Dplugin.cd.go.contrib.elastic-agent.docker.log.level=debug'
    volumes:
      - ./godata:/godata
      - ./gohome:/home/go
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gocd
    ports:
      - "8153:8153"
      - "8154:8154"

  agent:
    build:
      context: .
      dockerfile: docker/Dockerfile.agent
    env_file: .agent_env
    environment:
      GO_SERVER_URL: https://server:8154/go
      #AGENT_AUTO_REGISTER_KEY: 12345678-90ab-cdef-1234-567890abcdef
      AGENT_AUTO_REGISTER_RESOURCES: git,docker
      AGENT_AUTO_REGISTER_ENVIRONMENTS: default
    volumes:
      - ./gohome:/home/go
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gocd

  gitea:
    image: gitea/gitea:latest
    volumes:
      - ./gitea:/data
    networks:
      - gocd
    ports:
      - "3000:3000"
      - "10022:10022"

#  registry:
#    image: registry:latest
#    networks:
#      - gocd
#    ports:
#      - "5000:5000"

networks:
  gocd:
    driver: bridge
